spring.application.name=Ecommerce-Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/EcommerceDB
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=create
Jwt.secretKey=aw9o33mn492nvaospmdf34902fvdsvwqgwrdsofmwsanm0mrtasdfggsdf49y
deploy.env=development